name: Commit Intervals As A Service
run-name: Add git commits authored by ${{ github.actor }} in constant time intervals
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Initialize Environment Variables
        run: |
          echo GITHUB_REPOSITORY_NAME=${GITHUB_REPOSITORY#*/} >> $GITHUB_ENV
          echo GIT_SERVICE_BRANCH=service >> $GITHUB_ENV
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup Git Config
        run: |
          git config user.name ${{ github.actor }}
          git config user.email "${{ github.actor }}@noreply.github.com"
          git config alias.switchoc '!f() { git switch $1 2>/dev/null || git switch -c $1; }; f'
      - run: |
          # git remote set-url origin https://${{secrets.PAT}}@github.com/${{ github.repository }}.git
          # git pull
          git switchoc ${GIT_SERVICE_BRANCH}
          echo 'Hello' > test.txt
          git add .
          git commit -m 'test'
          # git remote -v
          echo 'pushing changes...'
          git push origin ${GIT_SERVICE_BRANCH}:${GIT_SERVICE_BRANCH}
