name: Commit Intervals As A Service
run-name: Add git commits authored by ${{ github.actor }} in constant time intervals
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Initialize Environment Variables
        run: |
          echo ::set-env name=GITHUB_REPOSITORY_NAME::${GITHUB_REPOSITORY#*/}
          echo ::set-env name=GIT_SERVICE_BRANCH::service
      - name: Setup Git Config
        run: |
          git config --global user.name ${{ github.actor }}
          git config --global user.email "${{ github.actor }}@noreply.github.com"
          git config alias.switchoc '!f() { git switch $1 2>/dev/null || git switch -c $1; }; f'
      - name: Attempt Clone
        run: git clone https://${{secrets.PAT}}@github.com/${{ github.repository }}.git
      - run: |
          cd ${GITHUB_REPOSITORY_NAME}
          # git remote set-url origin https://${{secrets.PAT}}@github.com/${{ github.repository }}.git
          # git pull
          git switchoc ${GIT_SERVICE_BRANCH}
          echo 'Hello' > test.txt
          git add .
          git commit -m 'test'
          # git remote -v
          echo 'pushing changes...'
          git push origin ${GIT_SERVICE_BRANCH}:${GIT_SERVICE_BRANCH}
